version: '3'

services:
  api:
    build: .
    depends_on:
      - postgres
      - redis
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    env_file:
      - ./.env

    environment:
      - DATABASE_HOSTNAME=localhost
      - DATABASE_POST=5433
      - DATABASE_PASSWORD=password123
      - DATABASE_NAME=Fastapi
      - DATABASE_USERNAME=postgres
    restart: on-failure
    
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=FastApi
    ports:
      - "5433:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

  redis:
    image: "redis:latest"
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redisdata:/data

  celery:
    build: .
    command: celery -A app.worker.celery worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app

volumes:
  postgres-db:
  redisdata:
